import React,{useEffect,useState} from "react";
import {ResponsiveContainer,RadarChart,PolarGrid,PolarAngleAxis,PolarRadiusAxis,Radar,Tooltip} from "recharts";
import {http} from "./api/client";
const score=value=>value==null?"—":Number(value).toFixed(1);
export default function OrganizationOverview({classId,refreshToken}){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[retry,setRetry]=useState(0);
 useEffect(()=>{let alive=true;setLoading(true);setError("");http.get(`/api/teacher/classes/${classId}/overview`).then(r=>{if(alive)setData(r)}).catch(e=>{if(alive)setError(e.message||"组织概览加载失败")}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[classId,refreshToken,retry]);
 return <section className="organization-overview"><header><h3>组织总体情况</h3>{data?.calculatedAt&&<small>统计时间：{new Date(data.calculatedAt).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"})}</small>}</header>{loading?<p role="status">正在统计组织情况…</p>:error?<div role="alert"><p>{error}</p><button onClick={()=>setRetry(v=>v+1)}>重新加载</button></div>:data&&<><div className="organization-overview-metrics">{[["组织人数",data.memberCount],["已评估人数",data.assessedCount],["平均综合分",score(data.averageScore)],["任务平均完成率",data.tasks?.averageCompletionRate==null?"—":`${score(data.tasks.averageCompletionRate)}%`]].map(([label,value])=><article key={label}><span>{label}</span><h3>{value}</h3></article>)}</div><div className="organization-overview-charts"><article><h3>组织六维平均水平</h3>{data.dimensions?.some(d=>d.score!=null)?<ResponsiveContainer width="100%" height={280}><RadarChart data={data.dimensions} outerRadius="65%"><PolarGrid stroke="#ddcfb9"/><PolarAngleAxis dataKey="dimension" tick={{className:"ripple-chart-label-10"}}/><PolarRadiusAxis domain={[0,100]} tick={false} axisLine={false}/><Tooltip/><Radar dataKey="score" name="组织平均" stroke="#3488bb" fill="#3488bb" fillOpacity={0.18}/></RadarChart></ResponsiveContainer>:<p>暂无有效能力数据，待学生完成测评后生成。</p>}<small>各项能力之和÷组织总人数；未评估成员计入人数，完全无人评估的维度显示暂无。</small></article><article><h3>能力等级分布</h3><div className="organization-level-distribution">{Object.entries(data.levelDistribution||{}).map(([level,count])=><div key={level}><span>{level==="L0"?"L0 · 未评估":level}</span><progress max={Math.max(1,data.memberCount||0)} value={count}/><b>{count} 人</b></div>)}</div><p>任务统计：已发布 {data.tasks?.publishedCount||0} 个，进行中 {data.tasks?.activeCount||0} 个。</p><small>完成率按每个任务发布时的目标学生名单计算，再取任务平均值；小灶目标为1人。</small></article></div></>}</section>
}
